# Generated by Django 5.2 on 2026-01-05 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorsubscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Gratuit'), ('pro', 'Pro')], default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorsubscription',
            name='max_products',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendorsubscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorsubscription',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='shops.vendor'),
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
